export const USER_ROLES = {
  USER: 'USER',
  ANALYST: 'ANALYST',
  ADMIN: 'ADMIN',
} as const;

export type UserRole = (typeof USER_ROLES)[keyof typeof USER_ROLES];

export const PERMISSIONS = {
  AUTH_READ_SELF: 'auth:read:self',
  PROFILE_READ_SELF: 'profile:read:self',
  PROFILE_WRITE_SELF: 'profile:write:self',
  PANEL_READ_SELF: 'panel:read:self',
  PANEL_WRITE_SELF: 'panel:write:self',
  DOCUMENT_PARSE_SELF: 'document:parse:self',
  SIMULATION_READ_SELF: 'simulation:read:self',
  SIMULATION_WRITE_SELF: 'simulation:write:self',
  AGENT_CHAT_SELF: 'agent:chat:self',
  OBSERVABILITY_READ: 'observability:read',
  DEV_INJECT: 'dev:inject',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ROLE_PERMISSION_MATRIX: Record<UserRole, Permission[]> = {
  USER: [
    PERMISSIONS.AUTH_READ_SELF,
    PERMISSIONS.PROFILE_READ_SELF,
    PERMISSIONS.PROFILE_WRITE_SELF,
    PERMISSIONS.PANEL_READ_SELF,
    PERMISSIONS.PANEL_WRITE_SELF,
    PERMISSIONS.DOCUMENT_PARSE_SELF,
    PERMISSIONS.SIMULATION_READ_SELF,
    PERMISSIONS.SIMULATION_WRITE_SELF,
    PERMISSIONS.AGENT_CHAT_SELF,
  ],
  ANALYST: [
    PERMISSIONS.AUTH_READ_SELF,
    PERMISSIONS.PROFILE_READ_SELF,
    PERMISSIONS.PROFILE_WRITE_SELF,
    PERMISSIONS.PANEL_READ_SELF,
    PERMISSIONS.PANEL_WRITE_SELF,
    PERMISSIONS.DOCUMENT_PARSE_SELF,
    PERMISSIONS.SIMULATION_READ_SELF,
    PERMISSIONS.SIMULATION_WRITE_SELF,
    PERMISSIONS.AGENT_CHAT_SELF,
    PERMISSIONS.OBSERVABILITY_READ,
  ],
  ADMIN: [
    PERMISSIONS.AUTH_READ_SELF,
    PERMISSIONS.PROFILE_READ_SELF,
    PERMISSIONS.PROFILE_WRITE_SELF,
    PERMISSIONS.PANEL_READ_SELF,
    PERMISSIONS.PANEL_WRITE_SELF,
    PERMISSIONS.DOCUMENT_PARSE_SELF,
    PERMISSIONS.SIMULATION_READ_SELF,
    PERMISSIONS.SIMULATION_WRITE_SELF,
    PERMISSIONS.AGENT_CHAT_SELF,
    PERMISSIONS.OBSERVABILITY_READ,
    PERMISSIONS.DEV_INJECT,
  ],
};

export function hasPermission(role: UserRole, permission: Permission): boolean {
  return ROLE_PERMISSION_MATRIX[role]?.includes(permission) ?? false;
}
