import { chromium } from 'playwright';
const browser = await chromium.launch({ headless: true });
const page = await (await browser.newContext()).newPage();
const email = `debug.${Date.now()}@example.com`;
const password = 'QAtest1234';
await page.goto('http://localhost:3000/register', { waitUntil: 'networkidle' });
const nameInput = page.locator('input[type="text"]').first();
const emailInput = page.locator('input[type="email"]').first();
const passwordInput = page.locator('input[type="password"]').first();
await nameInput.fill('QA Smoke');
await emailInput.fill(email);
await passwordInput.fill(password);
console.log('before', await nameInput.inputValue(), await emailInput.inputValue(), await passwordInput.inputValue());
await page.getByRole('button', { name: /continuar|crear/i }).first().click();
await page.waitForTimeout(1500);
console.log('after-url', page.url());
console.log('after', await nameInput.inputValue().catch(()=>''), await emailInput.inputValue().catch(()=>''), await passwordInput.inputValue().catch(()=>''));
const body = await page.locator('body').innerText();
console.log('body', body.slice(0,400));
await browser.close();
