export {
  MAX_BUDGET_ROWS,
  DEFAULT_BUDGET_ROWS,
  buildPersistableBudgetContext,
  collectBudgetDescendantIds,
  canonicalBudgetRowId,
  computeBudgetCompletion,
  computeBudgetInsights,
  computeBudgetSignals,
  computeBudgetTotals,
  createBudgetStarterRows,
  getEffectiveBudgetRows,
  mergeBudgetTemplate,
  normalizeBudgetRow,
  reconcileBudgetRows,
  inferBudgetFocusRowId,
  extractInferenceQuestionText,
  isBareBudgetAmountAnswer,
  resolveBudgetChatTargetRow,
} from '@financial-agent/shared';
export type { BudgetRow, BudgetTopExpense } from '@financial-agent/shared';
