export {
  MAX_BUDGET_ROWS,
  DEFAULT_BUDGET_ROWS,
  buildPersistableBudgetContext,
  collectBudgetDescendantIds,
  canonicalBudgetRowId,
  computeBudgetCompletion,
  computeBudgetInsights,
  computeBudgetSignals,
  computeBudgetTotals,
  createBudgetStarterRows,
  getEffectiveBudgetRows,
  mergeBudgetTemplate,
  mergeBudgetInitialRows,
  buildBudgetRowsFromProducts,
  hasBudgetProductSeedInput,
  normalizeBudgetRow,
  reconcileBudgetRows,
  isBudgetProductSeededRows,
  inferBudgetFocusRowId,
  extractInferenceQuestionText,
  isBareBudgetAmountAnswer,
  resolveBudgetChatTargetRow,
} from '@financial-agent/shared';
export type { BudgetRow, BudgetTopExpense, BudgetProductSnapshot } from '@financial-agent/shared';
