export type FinancialServiceOption = {
  id: string;
  label: string;
  category: 'banking' | 'cards' | 'insurance' | 'investments' | 'credit';
  description: string;
};

export const FINANCIAL_SERVICE_OPTIONS: FinancialServiceOption[] = [
  {
    id: 'checking-account',
    label: 'Cuenta corriente',
    category: 'banking',
    description: 'Movimientos bancarios, transferencias y cargos recurrentes.',
  },
  {
    id: 'vista-account',
    label: 'Cuenta vista / prepago',
    category: 'banking',
    description: 'Flujo diario, pagos de servicios y transferencias menores.',
  },
  {
    id: 'debit-card',
    label: 'Tarjeta de debito',
    category: 'cards',
    description: 'Consumos cotidianos y control de gasto transaccional.',
  },
  {
    id: 'credit-card',
    label: 'Tarjeta de credito',
    category: 'cards',
    description: 'Facturacion, cuotas, intereses y comisiones asociadas.',
  },
  {
    id: 'line-of-credit',
    label: 'Linea de credito',
    category: 'credit',
    description: 'Uso de sobregiro, costo financiero y carga mensual.',
  },
  {
    id: 'consumer-loan',
    label: 'Credito de consumo',
    category: 'credit',
    description: 'Cuotas, seguros asociados y comportamiento de pago.',
  },
  {
    id: 'mortgage-loan',
    label: 'Credito hipotecario',
    category: 'credit',
    description: 'Dividendo, tasa, seguros obligatorios y saldo vigente.',
  },
  {
    id: 'auto-loan',
    label: 'Credito automotriz',
    category: 'credit',
    description: 'Cuota mensual, seguro del vehiculo y costo total.',
  },
  {
    id: 'insurance',
    label: 'Seguros',
    category: 'insurance',
    description: 'Prima mensual, coberturas y siniestros relevantes.',
  },
  {
    id: 'mutual-fund',
    label: 'Fondos mutuos',
    category: 'investments',
    description: 'Aportes, rescates y rendimiento historico.',
  },
  {
    id: 'brokerage',
    label: 'Acciones / ETF',
    category: 'investments',
    description: 'Posiciones, valorizacion y perfil de riesgo.',
  },
  {
    id: 'term-deposit',
    label: 'Depositos a plazo',
    category: 'investments',
    description: 'Plazo, tasa pactada y vencimientos.',
  },
];

export const CHILE_FINANCIAL_INSTITUTIONS: string[] = [
  'BancoEstado',
  'Banco de Chile',
  'Banco Santander Chile',
  'Banco de Credito e Inversiones (BCI)',
  'Scotiabank Chile',
  'Itaú Chile',
  'Banco Security',
  'Banco BICE',
  'Banco Internacional',
  'Banco Falabella',
  'Banco Ripley',
  'Banco Consorcio',
  'Banco BTG Pactual Chile',
  'JP Morgan Chase Bank N.A. Chile',
  'Bank of China Chile',
  'Mizuho Bank Chile',
  'MUFG Bank Chile',
  'Banco do Brasil S.A. Chile',
  'Banco de la Nacion Argentina Chile',
  'Coopeuch',
  'Oriencoop',
  'Capual',
  'Detacoop',
  'Caja Los Andes',
  'Caja La Araucana',
  'Caja 18',
  'Caja Los Heroes',
  'Consorcio Seguros',
  'BICE Vida',
  'MetLife Chile',
  'SURA Chile',
  'HDI Seguros',
  'MAPFRE Chile',
  'Zurich Chile',
  'Chubb Seguros Chile',
  'Renta Nacional',
  'Principal Chile',
  'LarrainVial',
  'Banchile Inversiones',
  'BTG Pactual Wealth Management',
  'Renta4 Chile',
  'Fintual',
  'Racional',
  'Tenpo',
  'Mach',
  'Mercado Pago',
  'Copec Pay',
];
