export const INTERVIEW_TOTAL_LIMIT_SEC = 180;
export const INTERVIEW_TOTAL_LIMIT_MINUTES = Math.ceil(INTERVIEW_TOTAL_LIMIT_SEC / 60);
export const INTERVIEW_CLOSEOUT_BUFFER_SEC = 25;
export const INTERVIEW_MAX_CALLS_PER_USER = 1;
